In [69]:
import numpy as np

In [72]:
"shift + enter"

'shift + enter'

In [73]:
"alt+enter"

'alt+enter'

In [6]:
my_list = [1,2,3]

In [8]:
my_list

[1, 2, 3]

In [17]:
arr = np.array(my_list)

In [19]:
arr

array([1, 2, 3])

In [24]:
my_mat = [[1,2,3],[4,5,6],[3,2,1]]

2 dimentional array  2 brackets

In [22]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [3, 2, 1]])

In [26]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [30]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [38]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [40]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [43]:
np.random.rand(5)

array([0.484277  , 0.78483893, 0.82198607, 0.82388853, 0.83302881])

In [45]:
np.random.rand(5,2)

array([[0.76134316, 0.56397811],
       [0.34040466, 0.74791811],
       [0.00224808, 0.63794084],
       [0.24598582, 0.38499156],
       [0.24598928, 0.89333549]])

In [47]:
np.random.randn(2,2)

array([[-1.03643599,  1.38719068],
       [-1.28340143,  1.50909072]])

In [51]:
np.random.randint(0,100,10)

array([67, 34, 73,  7, 66, 76, 23, 61, 34, 15])

In [52]:
arr = np.arange(20)

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [55]:
ranarr= np.random.randint(1,30,10)

In [56]:
ranarr

array([28,  8,  1, 20,  1, 29, 22,  1, 10,  8])

In [58]:
arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [59]:
ranarr

array([28,  8,  1, 20,  1, 29, 22,  1, 10,  8])

In [60]:
ranarr.max()

29

In [61]:
ranarr.min()

1

In [62]:
ranarr.argmax()

5

In [63]:
ranarr.argmin()

2

In [64]:
arr.shape

(20,)

In [66]:
arr =arr.reshape(4,5)

In [67]:
arr.shape

(4, 5)

In [68]:
arr.dtype

dtype('int64')

In [74]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [79]:
arr = np.arange(8)

In [80]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [81]:
arr[7]

7

In [82]:
arr[1:5]

array([1, 2, 3, 4])

In [83]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [84]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [85]:
arr[,6]

SyntaxError: invalid syntax (<ipython-input-85-2363816c4c76>, line 1)

In [86]:
arr[5:]

array([5, 6, 7])

In [87]:
arr[0:5] = 100

In [88]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7])

In [90]:
arr = np.arange(0,10)

In [91]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
slice_of_arr = arr[0:5]

In [97]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [101]:
slice_of_arr = 10

In [105]:
slice_of_arr = arr[0:5]

In [106]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [107]:
slice_of_arr[:] = 10

In [108]:
slice_of_arr

array([10, 10, 10, 10, 10])

In [109]:
arr

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9])

In [110]:
arr_copy = arr.copy()

In [111]:
arr_copy

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9])

In [113]:
arr_copy = np.arange(0,10)

In [114]:
arr_copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
arr

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9])

Indexing 2d array

In [117]:
arr_2d = np.array([[2,5,10],[6,5,2],[8,9,4]])

In [118]:
arr_2d

array([[ 2,  5, 10],
       [ 6,  5,  2],
       [ 8,  9,  4]])

In [119]:
arr_2d[0][0]

2

In [123]:
arr_2d[:]

array([[ 2,  5, 10],
       [ 6,  5,  2],
       [ 8,  9,  4]])

In [127]:
arr_2d[2,2]

4

In [138]:
arr_2d

array([[ 2,  5, 10],
       [ 6,  5,  2],
       [ 8,  9,  4]])

slicing

In [129]:
arr_2d[:2,1:]

array([[ 5, 10],
       [ 5,  2]])

In [136]:
 arr_2d[1:,:2]

array([[6, 5],
       [8, 9]])

In [137]:
arr_2d[:2]

array([[ 2,  5, 10],
       [ 6,  5,  2]])

conditional selection

In [139]:
arr = np.arange(0,10)

In [140]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [143]:
bool_arr = arr > 5

In [144]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [145]:
arr[arr>5]

array([6, 7, 8, 9])

In [146]:
arr_2d = np.arange(50).reshape(5,10)

In [147]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [149]:
arr_2d[2:4,5:8]

array([[25, 26, 27],
       [35, 36, 37]])

NumPy Operations

In [150]:
arr = np.arange(0,11)

In [151]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [152]:
arr -arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [153]:
arr +arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [154]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [155]:
arr / arr

/home/satyendra/.local/lib/python3.5/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [156]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [157]:
arr ** arr

array([          1,           1,           4,          27,         256,
              3125,       46656,      823543,    16777216,   387420489,
       10000000000])

In [158]:
1/arr

/home/satyendra/.local/lib/python3.5/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [159]:
arr.max()

10

In [160]:
arr.min()

0

In [161]:
arr[arr]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [163]:
arr -100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [164]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [165]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [166]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [167]:
np.max(arr)

10

In [168]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [169]:
np.log(arr)

/home/satyendra/.local/lib/python3.5/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

Get the sum of all the columns in mat

In [170]:
mat = np.arange(20).reshape(4,5)

In [171]:
mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [172]:
mat.sum(axis=0)

array([30, 34, 38, 42, 46])

In [175]:
np.arange(1).respae(10,10)

AttributeError: 'numpy.ndarray' object has no attribute 'respae'